trigger: # Correção: ttrigger -> trigger
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerVersion: '20.10.24'
  ARM_SUBSCRIPTION_NAME: 'Azure'
  ARM_RESOURCE_GROUP_NAME: 'NomeDoSeuGrupoDeRecursos'
  APP_SERVICE_NAME: 'NomeDoSeuAppService'
  DOCKER_HUB_USERNAME: $(dockerHubUsername)
  IMAGE_NAME: $(imageName)

stages:
- stage: Build
  displayName: 'Build and push image to Docker Hub'
  jobs:
  - job: Build
    steps:
    # ... (suas etapas de build)

- stage: Deploy  # Linha 20 corrigida (removendo linha em branco)
  displayName: 'Deploy to App Service'
  dependsOn: Build
  variables:
    DOCKER_IMAGE_NAME: '$(DOCKER_HUB_USERNAME)/$(IMAGE_NAME):$(Build.BuildId)'
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to App Service'
            inputs:
              azureSubscription: $(ARM_SUBSCRIPTION_NAME)
              appType: webApp
              appName: $(APP_SERVICE_NAME)
              imageName: $(DOCKER_IMAGE_NAME)