trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker'
  inputs:
    dockerVersion: 'latest'

- task: Docker@2
  displayName: 'Build and push image to Docker Hub'
  inputs:
    command: buildAndPush
    repository: '$(dockerHubUsername)/$(imageName)'
    tags: '$(Build.BuildId)'
    Dockerfile: '**/Dockerfile'
    username: '$(dockerHubUsername)'
    password: '$(dockerHubPassword)'
