trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerVersion: '20.10.24' # Ou a versão estável que você preferir

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker'
  inputs:
    dockerVersion: '$(dockerVersion)'

- task: Docker@2
  displayName: 'Build and push image to Docker Hub'
  inputs:
    command: buildAndPush
    repository: '$(dockerHubUsername)/$(imageName)'
    tags: '$(Build.BuildId)'
    Dockerfile: '**/Dockerfile'
    username: '$(dockerHubUsername)'
    password: '$(dockerHubPassword)'
